### ISSUE TITLE
I change the ASK value, after changing it in a d function it fails in integrity check

### ISSUE THREAD

**Issue by moodleexpert** [easonlin404/ksm#25]
I change the ASK value in a d function. It gives me error check the integrity of the SPC failed

**Comment by easonlin404** [comment]
Hi @moodleexpert do you replace with public key/private key which is own by your apple application account?

**Comment by moodleexpert** [comment]
@easonlin404 Yes

**Comment by moodleexpert** [comment]
I have got ask.bin file which length is 16

**Comment by moodleexpert** [comment]
it is working using d.CP_D_Function{} . Thanks for support
